### ISSUE TITLE
App crashes on TextInput changes

### ISSUE THREAD

**Issue by hotrush** [react-native-tvos/react-native-tvos#257]
App crashes in emulator when i'm adding TextInput and trying to input some text. From logs I found the next error:

```
01-22 21:06:49.419  5376  5376 E AndroidRuntime: FATAL EXCEPTION: main
01-22 21:06:49.419  5376  5376 E AndroidRuntime: Process: com.testapp, PID: 5376
01-22 21:06:49.419  5376  5376 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at com.facebook.react.views.textinput.ReactTextInputManager$4.onEditorAction(ReactTextInputManager.java:1097)
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at android.widget.TextView.onEditorAction(TextView.java:7149)
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:159)
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:577)
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:111)
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-22 21:06:49.419  5376  5376 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

## React Native version:
```
    react-native-tvos:  0.66.3-0
```

## Steps To Reproduce

1. Just create an empty project from this template https://github.com/react-native-tvos/react-native-template-typescript-tv

```
npx react-native init MyApp --template react-native-template-typescript-tv
```

2. Update tvos lib to the latest version

3. Modified `App.tsx` to have the next code additionally to existing 

```
const [val, setVal] = useState('asdad');

<View>
    <TextInput value={val} onChangeText={setVal} />
</View>
```

4. Run in emulator - app crashes on any changes in text input

https://user-images.githubusercontent.com/1247004/150650608-1f7186a6-e81c-436a-947f-6c0a98919b20.mov

## Expected Results
App won't crash

**Comment by douglowder** [comment]
This is the same as https://github.com/facebook/react-native/issues/30346 -- thanks for supplying a reliable repro case

**Comment by hotrush** [comment]
After some research i found that it happens only when I use virtual keyboard, with hardware keyboard seems to be ok

**Comment by douglowder** [comment]
Testing with 0.66.3-1, I don't reproduce a crash, either with virtual or physical keyboard.

```typescript
const App = () => {
  const [val, setVal] = React.useState("test");
  return (
    <>
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={styles.scrollView}>
          <Header />
        <View>
            <TextInput value={val} onChangeText={setVal} />
        </View>

```
