### ISSUE TITLE
Jest setup fails when using this as a Jest preset

### ISSUE THREAD

**Issue by JackAlexRose** [react-native-tvos/react-native-tvos#280]
## Description
My company is using this NPM package in our TVOS and Android TV project. I am setting up Jest testing in a Jest projects solution as our react native package exists inside a monorepo.

## React Native version:
From my package.json: "react-native": "npm:react-native-tvos@0.66.3-2",

## Steps To Reproduce
Below is my jest.config.js

```
'use strict'
const baseConfig = require('../../jest.config.base');
const { defaults: tsjPreset } = require('ts-jest/presets');
const packageName = "native";

module.exports = {
  ...tsjPreset,
  ...baseConfig,
  globals: {
    'ts-jest': {
      tsConfig: '<rootDir>/tsconfig.json',
      babelConfig: true,
      diagnostics: false,
    },
  },
  roots: [
    './',
  ],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
  ],
  preset: "react-native",
  setupFilesAfterEnv: ["@testing-library/jest-native/extend-expect"],
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': 'ts-jest',
  },
  transformIgnorePatterns: [
    "/node_modules/(?!(react-router-native|react-native)/)"
  ],
  testEnvironment: 'jsdom',
  name: packageName,
  displayName: packageName,
  rootDir: './',
};
```

and my package.json:

```
{
  "name": "<obscured>",
  "version": "0.3.0",
  "private": true,
  "scripts": {
    "android": "react-native run-android --variant \"localDebug\" --appIdSuffix \"local\"",
    "tvos": "react-native run-ios --simulator \"Apple TV\" --scheme \"jijidemotmdb-tvOS\" --configuration \"Local-Debug\"",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "<obscured>": "0.7.0-mainline.1642674980",
    "<obscured>": "0.7.0-mainline.1642674980",
    "<obscured>": "0.4.1",
    "history": "5.0.0",
    "<obscured>": "0.3.0",
    "lottie-ios": "3.1.8",
    "lottie-react-native": "3.5.0",
    "metro-config": "0.59.0",
    "react": "16.13.1",
    "react-native": "npm:react-native-tvos@0.66.3-2",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-svg": "12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-video": "5.2.0",
    "react-router": "5.2.0",
    "react-router-native": "5.2.0"
  },
  "devDependencies": {
    "@babel/core": "7.13.15",
    "@babel/plugin-transform-runtime": "^7.17.0",
    "@babel/preset-env": "^7.16.11",
    "@babel/preset-react": "^7.16.7",
    "@babel/preset-typescript": "^7.16.7",
    "@babel/runtime": "7.13.10",
    "@testing-library/jest-native": "^4.0.4",
    "@testing-library/react-native": "^9.0.0",
    "@types/jest": "26.0.22",
    "@types/react": "17.0.3",
    "@types/react-native": "0.63.52",
    "@types/react-native-video": "5.0.10",
    "@types/react-router-native": "5.1.0",
    "@types/react-test-renderer": "17.0.1",
    "babel-jest": "^27.5.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "jest": "^27.5.1",
    "jest-svg-transformer": "^1.0.0",
    "metro-react-native-babel-preset": "0.59.0",
    "react-native-typescript-transformer": "1.2.13",
    "react-test-renderer": "16.13.1",
    "ts-jest": "^27.1.3",
    "ts-loader": "^9.2.8",
    "typescript": "4.2.4"
  },
  "resolutions": {
    "react-devtools": "4.13.4"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}

```

And finally my babel.config.js:
```
module.exports = {
  presets: [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript",
    "module:metro-react-native-babel-preset"
  ],
  plugins: [
    [
      "@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ]
}
```
Now running Jest results in the following error:
```
Test suite failed to run

    ReferenceError: <obscured>packages/native/node_modules/react-native/jest/setup.js: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: __assign
    Allowed objects: AbortController, AbortSignal, AggregateError, Array, ArrayBuffer, Atomics, BigInt, BigInt64Array, BigUint64Array, Boolean, Buffer, DataView, Date, Error, EvalError, Event, EventTarget, FinalizationRegistry, Float32Array, Float64Array, Function, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, MessageChannel, MessageEvent, MessagePort, NaN, Number, Object, Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set, SharedArrayBuffer, String, Symbol, SyntaxError, TextDecoder, TextEncoder, TypeError, URIError, URL, URLSearchParams, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakRef, WeakSet, WebAssembly, __dirname, __filename, arguments, atob, btoa, clearImmediate, clearInterval, clearTimeout, console, decodeURI, decodeURIComponent, encodeURI, encodeURIComponent, escape, eval, expect, exports, global, globalThis, isFinite, isNaN, jest, module, parseFloat, parseInt, performance, process, queueMicrotask, require, setImmediate, setInterval, setTimeout, undefined, unescape.
    Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` (case insensitive) are permitted.

      91 | })
      92 |     .mock('../Libraries/Components/TextInput/TextInput', function () {
    > 93 |     return mockComponent('../Libraries/Components/TextInput/TextInput', __assign(__assign({}, MockNativeMethods), { isFocused: jest.fn(), clear: jest.fn(), getNativeRef: jest.fn() }));
         |                                                                         ^^^^^^^^
      94 | })
      95 |     .mock('../Libraries/Modal/Modal', function () {
      96 |     return mockComponent('../Libraries/Modal/Modal');

      at File.buildCodeFrameError (node_modules/@babel/core/lib/transformation/file/file.js:240:12)
      at NodePath.buildCodeFrameError (node_modules/@babel/traverse/lib/path/index.js:139:21)
```
Maybe the react-native-tvos Jest setup script doesn't work with the current version of Jest? 

I've tried downgrading all my Jest related packages but I can only go so far back before a ts-jest preset no longer exists or similar errors.

If someone has a working Jest setup with this package, I would love to see an example jest config and other required files/packages as i'm just doing the initial setup so i'm not married to any of the extra components here.

**Comment by douglowder** [comment]
@JackAlexRose thanks for the bug report. Is this something that can be reproduced with a new project created with a TS template, e.g.

```bash
react-native init TestApp --template=react-native-typescript-template-tv
```

Alternatively, do you have a demo project that reproduces this error?

Do you see this error in RN core 0.67 release, or 0.68 release candidates?

**Comment by douglowder** [comment]
Your `react-test-renderer` version is too low for your `react` version I think
