### ISSUE TITLE
react-native-tvos/rnn-starter-tv gradle error

### ISSUE THREAD

**Issue by iDVB** [react-native-tvos/react-native-tvos#397]
### Description

Wasn't sure where to document this. 
I'm very new to RN but have a working app for Android TV and was very hopeful to use bits of the https://github.com/react-native-tvos/rnn-starter-tv sample app.

However, when I try to launch the app in the emulator I get...
```
yarn run v1.22.17
$ yarn android:adb && npx react-native run-android
$ adb reverse tcp:8081 tcp:8081
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1493 file(s) to forward-jetify. Using 12 workers...
info Starting JS server...
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :react-native-navigation
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Task :app:checkDebugAarMetadata FAILED
68 actionable tasks: 62 executed, 6 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.appcompat:appcompat:1.4.1.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/a768d3189fbb0a5a64830c14191d9f07/appcompat-1.4.1/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.appcompat:appcompat-resources:1.4.1.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/be839956c4b9020cb2ac80de11e56373/jetified-appcompat-resources-1.4.1/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.emoji2:emoji2-views-helper:1.0.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/6a5a0ae5e53122d22f37a72299b0b97a/jetified-emoji2-views-helper-1.0.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.emoji2:emoji2:1.0.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/de5bd7ce4042dcc283cafd5aadbe447d/jetified-emoji2-1.0.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.lifecycle:lifecycle-process:2.4.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/9b793705956ad00a20293748fafb6322/jetified-lifecycle-process-2.4.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.tracing:tracing:1.1.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/c9713f0cb21c407eb3ef4f75be754f42/jetified-tracing-1.1.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.core:core:1.7.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/505987f6d923ba5d51af141811f3190a/core-1.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.lifecycle:lifecycle-runtime:2.4.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/8dcf97139682eb310a2500a331b041dd/lifecycle-runtime-2.4.0/META-INF/com/android/build/gradle/aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.appcompat:appcompat:1.4.1.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/a768d3189fbb0a5a64830c14191d9f07/appcompat-1.4.1/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.appcompat:appcompat-resources:1.4.1.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/be839956c4b9020cb2ac80de11e56373/jetified-appcompat-resources-1.4.1/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.emoji2:emoji2-views-helper:1.0.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/6a5a0ae5e53122d22f37a72299b0b97a/jetified-emoji2-views-helper-1.0.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.emoji2:emoji2:1.0.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/de5bd7ce4042dcc283cafd5aadbe447d/jetified-emoji2-1.0.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.lifecycle:lifecycle-process:2.4.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/9b793705956ad00a20293748fafb6322/jetified-lifecycle-process-2.4.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.tracing:tracing:1.1.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/c9713f0cb21c407eb3ef4f75be754f42/jetified-tracing-1.1.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.core:core:1.7.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/505987f6d923ba5d51af141811f3190a/core-1.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.lifecycle:lifecycle-runtime:2.4.0.
        AAR metadata file: /Users/dvanbrunt/.gradle/caches/transforms-2/files-2.1/8dcf97139682eb310a2500a331b041dd/lifecycle-runtime-2.4.0/META-INF/com/android/build/gradle/aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s

    at makeError (/Users/dvanbrunt/Projects/MoviePosters/rnn-starter-tv/node_modules/execa/index.js:174:9)
    at /Users/dvanbrunt/Projects/MoviePosters/rnn-starter-tv/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/Users/dvanbrunt/Projects/MoviePosters/rnn-starter-tv/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/dvanbrunt/Projects/MoviePosters/rnn-starter-tv/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

 Is there a better more up to date example of an Android TV app that showcases a number of helpful libs?

### Version

0.64.2-4

### Output of `npx react-native info`

```
System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 113.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v18.8.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
    Watchman: 2022.10.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.64.2-4 
  npmGlobalPackages:
    *react-native*: Not Found
   ```

### Steps to reproduce

1. Clone repo
2. `yarn`
3. Launch Android TV Simulator from Android Studio
4. `yarn android`
5. err

### Snack, code example, screenshot, or link to a repository

https://github.com/react-native-tvos/rnn-starter-tv

**Comment by douglowder** [comment]
I think you can fix this by just opening `android/build.gradle` and changing `compileSdkVersion` to 31.

Sorry I have not had a chance to update this project in some time.

**Comment by iDVB** [comment]
Thanks! I'll give that a go.

@douglowder Can you point me in the direction of a few things? 
- what in that codebase is enabling the use of Typescript. My codebase is plain JS and I would love to port it over to TS.
- Any idea why I can run `react-native run-android --verbose` on my own codebase and it launches the android TV emulator and pushes the app in to test. But this rnn-starter-tv code base requires us to manually open Android Studio and launch the emulator?

**Comment by douglowder** [comment]
For an idea of what your repo should look like for Typescript, take a look at https://github.com/react-native-tvos/react-native-template-typescript-tv . You can try that out by creating a new app with

```
react-native init TSTest --template=react-native-template-typescript-tv
```

It's very similar to the Typescript template for RN (`react-native-template-typescript`) -- there is an additional file in the TV repo that you need to import (`tvos-types.d.ts`).

There is work happening now to fully integrate Typescript support into the main RN repo over the next few releases starting with 0.71, and the TV repo will include those changes.

I would have to look at what your codebase is doing to determine why yours behaves differently from the rnn-starter repo.

**Comment by wouterds** [comment]
This seems related to https://github.com/react-native-tvos/react-native-tvos/issues/386, applying this patch in the project fixes it https://github.com/wouterds/react-native-tv-example/commit/88f731e. Probably this will get fixed eventually when react-native-tvos is synced with the upstream react-native repository or when the patch is applied in react-native-tvos itself.

**Comment by wouterds** [comment]
I am going to close this issue for now as there's a workaround available (see above) and the issue has been fixed upstream but is not yet available in a release in react-native-tvos.
