### ISSUE TITLE
Codegen mkdir fails in ios build

### ISSUE THREAD

**Issue by peraronsson** [react-native-tvos/react-native-tvos#489]
### Description

Using React Native new architecture on Mac M1 Monterey, Xcode 13.4.1.

1. Build for tvos (ios folder) fails:

Using CLI `npx react-native run-ios --scheme Example-tvOS --simulator "Apple TV"` results in 

`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening Example.xcworkspace.`

Building in Xcode, as suggested, results in:

```
[Codegen] >>>>> Processing FBReactNativeSpec
[Codegen] Generated schema: /var/folders/99/ydwzccf57lj2md5z9nq22c080000gn/T/FBReactNativeSpec1Dmn7v/schema.json
{ Error: ENOENT: no such file or directory, mkdir '/Users/xxx/Library/Developer/Xcode/DerivedData/Example-grxxtymfbsfkktfsptjfzffazfzd/Build/Intermediates.noindex/Pods.build/Debug-appletvsimulator/React-Codegen-tvOS.build/DerivedSources/generated/source/codegen/out/build/generated/ios/FBReactNativeSpec'
    at Object.fs.mkdirSync (fs.js:885:18)
    at libraries.forEach.library (/Users/xxx/Workspace/react-native-tv-example/node_modules/react-native/scripts/generate-artifacts.js:274:10)
    at Array.forEach (<anonymous>)
    at main (/Users/xxx/Workspace/react-native-tv-example/node_modules/react-native/scripts/generate-artifacts.js:221:15)
    at Object.<anonymous> (/Users/xxx/Workspace/react-native-tv-example/node_modules/react-native/scripts/generate-artifacts.js:318:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/Users/xxx/Library/Developer/Xcode/DerivedData/Example-grxxtymfbsfkktfsptjfzffazfzd/Build/Intermediates.noindex/Pods.build/Debug-appletvsimulator/React-Codegen-tvOS.build/DerivedSources/generated/source/codegen/out/build/generated/ios/FBReactNativeSpec' }


[Codegen] Done.
Command PhaseScriptExecution failed with a nonzero exit code
```
The very long path exists up until /out/, so it's the last part of the path which is missing: `build/generated/ios/FBReactNativeSpec`

3. I also noticed this in the build logs:
`Node found at: /usr/local/bin/node`
The system node is v8.9.4. I'm using nvm and node 18.9 otherwise in this project.

### Version

0.69.8-1

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 164.22 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/xxx/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /Users/xxx/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.8-1 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

https://reactnative.dev/docs/environment-setup?platform=ios&os=macos
https://www.npmjs.com/package/react-native-tvos

`export RCT_NEW_ARCH_ENABLED=1`

Updated flipper due to this issue:

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from react-native-flipper@0.125.0
npm ERR! node_modules/react-native-flipper
npm ERR!   dev react-native-flipper@"^0.125.0" from the root project
```

Using:
"react-native-flipper": "^0.189.0",

```
npm install --legacy-peer-deps
cd ios
pod install
cd ..
npx react-native run-ios --scheme Example-tvOS --simulator "Apple TV"
```

Build fails, so I opened the ios project in Xcode and applied suggested modifications. Build with Xcode also fails with the reported error above.

**Comment by douglowder** [comment]
Most likely, you switched to Fabric (`export RCT_NEW_ARCH_ENABLED=1`) and did not delete the previous build directory first before attempting another build.

I don't think Flipper installation should make any difference, as it does not work on tvOS and it is not enabled in the Podfile.
